name: Build & Publish

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        # allow targeting a build against any branch
        ref: ${{ github.event.client_payload.target_ref }}
    - uses: nxtlvlsoftware/docker-pmmp-build-action@master
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: ${{ github.event.client_payload.tag }}
