name: Build & Publish

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    # only run if the event action is build & publish
    if: github.event.action == 'build-publish'

    steps:
    - uses: actions/checkout@v1
      with:
        # allow targeting a build against any branch
        ref: ${{ github.event.client_payload.target_ref }}
    - uses: ./.github/actions/build
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag: ${{ github.event.client_payload.tag }}
